# Node.js with React
# Build a Node.js project that uses React.

# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn run build
  displayName: 'yarn install and build'

- script: |
    docker build -t $(dockerId)/$(imageName):$(Build.BuildNumber) .
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName)

# - task: Docker@2
#   inputs:
#     containerRegistry: 'DefaultDockerRegistry'
#     command: 'login'
#   displayName: 'Docker login'

# - task: Docker@2
#   inputs:
#     repository: 'chiller-monitor'
#     command: 'build'
#     Dockerfile: '**/Dockerfile'
#   displayName: 'Docker building'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'DefaultDockerRegistry'
#     repository: 'chiller-monitor'
#     command: 'push'
#   displayName: 'Docker push to registry'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'DefaultDockerRegistry'
#     command: 'logout'
#   displayName: 'Docker logout'